--- 
title: "Exploring Fake News through LIAR dataset"
author: "Andrew Schaefer, Angad Nandwani and Ayush Sinha "
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Recently, the consumption of global news and its authenticity has become a considerable challenge. Social Media platforms like Facebook and Twitter enables us to access news anywhere, but they also have the potential to spread misinformation. This has a negative impact on the society, thereby making it necessary to verify the accuracy of news.

Automatic fake news detection is a challenging problem in deception detection, and it has tremendous potential on real-world political and social impacts. One of the datasets which allow us to build models and predict fake news is Liar Detection. This dataset has has 12,800 human labelled short statements in various contexts related to politics, and useful for the fact-checking research for news. In this project, we have used this dataset to explore the following questions/statements through exploratory data analysis.  

**Questions/Statements**

    1) Which positions of authority lead to Fake & Factual information? 
       Which party tends to spread Fake News more?

    2) What are the most selected Topics/Subjects selected by each Speaker 
       which has the highest tendency of spreading Fake News?

    3) Which states are spreading the most false news, 
       also noting the number of different speakers involved in 
       spreading Fake News?
  
    4) Which method of communication has resulted in the most Fake News spread by state?

    5) Correlations, Clusters & Outliers observed for different Venues/Platforms 
       in spreading Fake News for each State.

    6) Count of Words in a Statement in relation with its Label.
    
    7) What are the proportions of fake news for each state?
    
    8) What are the states with maximum proportions of fake news and in what subject?
    
    9) Distribution of Factual News with respect to state
    
    10) Which subject has the most concentrated fake news?
    
    11) Origin of Fake Vs Factual News with respect to Venue, Party & Job Title


Overall, through visualization, we have tried to find out the most reliable method of receiving correct information, which platforms we can pay attention to for controversial topics, and the suspicious figures we should avoid for getting the correct information.


**References**
1)  Ternion: An Autonomous Model for Fake News Detection - "Noman Islam, Asadullah Shaikh, Asma Qaiser, Yousef Asiri, Sultan Almakdi, Adel Sulaiman Verdah Moazzam and Syeda Aiman Babar".

2) "Liar, Liar Pants on Fire": A New Benchmark Dataset for Fake News Detection - William Yang Wang

3) John A. Bernau, PHD - Research Blog on Text Analysis

4) Few links that we used for Interactivity Game :-
  A: http://bl.ocks.org/jfreels/6734823
  B: https://www.d3-graph-gallery.com/graph/interactivity_button.html
  C: http://learnjsdata.com/read_data.html

